version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      dev-deps-major:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "major"
      dev-deps-non-major:
        dependency-type: "development"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      deps-major:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "major"
      deps-non-major:
        dependency-type: "production"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      github-actions-major:
        patterns:
          - "*"
        update-types:
          - "major"
      github-actions-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "daily"
    groups:
      docker-major:
        patterns:
          - "*"
        update-types:
          - "major"
      docker-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"
