allowBuilds:
  esbuild: true

minimumReleaseAgeExclude:
  - '@team-internet/semantic-release-plugins@1.0.6'
  - '@types/node@26.0.0'

onlyBuiltDependencies:
  - esbuild

overrides:
  diff: "8.0.3"
  serialize-javascript: "7.0.3"
  serialize-javascript@<7.0.5: '>=7.0.5'
